import abc
import math
from abc import ABC
import functools

from jax import numpy as jnp, lax, random
import numpy as onp

from lcd_clipr.utils.partial import vmap_chunk


class SDE(ABC):
    """
    Core class that handles SDE simulation.
    Subclasses have to implement `drift` and `diffusion` methods.

    Args:
        wiener_procs: number of Wiener processes to use for SDE simulation
        is_nonnegative: whether the SDE is constrained to be nonnegative
        dt: timestep for SDE simulation
        thinning: thinning factor for SDE simulation
        n_samples_burnin: number of samples to discard from SDE simulation
        anneal_steps: number of steps to run at a given noise level during annealing
        rollouts_shape: shape of the parallel rollouts of the SDE simulation
        anneal: whether to anneal the noise level during training
        sim_env_chunk_size: chunk size for vmap in SDE simulation
    """

    def __init__(
        self,
        wiener_procs,
        is_nonnegative=False,
        dt=0.01,
        thinning=50,
        n_samples_burnin=300,
        rollouts_shape=(1,),
        anneal_dt=0.01,
        anneal_steps=100,
        anneal=True,
        anneal_scales=None,
        sim_env_chunk_size=None,
    ):
        # simulation parameters
        self.dt = dt
        self.thinning = thinning
        self.wiener_procs = wiener_procs
        self.n_samples_burnin = n_samples_burnin
        self.rollouts_shape = rollouts_shape
        self.is_nonnegative = is_nonnegative

        self.anneal = anneal
        self.anneal_dt = anneal_dt
        self.anneal_steps = anneal_steps
        self.anneal_scales = anneal_scales
        self.sim_env_chunk_size = sim_env_chunk_size


    @abc.abstractmethod
    def drift(self, *, param, x, diffusion_time, noise_scale, mask_train, mask_query):
        """
        Args:
            param: PyTree
            x: [..., d]
            diffusion_time: diffusion annealing time
            noise_scale: diffusion annealing noise scale
            mask_train: [m, d]: training intervention mask
            mask_query: [d,]: query intervention mask

        Returns:
            f(x): [..., d]
        """
        pass


    @abc.abstractmethod
    def diffusion(self, *, param, x, diffusion_time, noise_scale, mask_train, mask_query):
        """
        Args:
            param: PyTree
            x: [..., d]
            diffusion_time: diffusion annealing time
            noise_scale: diffusion annealing noise scale
            mask_train: [m, d]: training intervention mask
            mask_query: [d,]: query intervention mask

        Returns:
            sigma(x): [..., d, wiener_procs]
        """
        pass


    def _simulate_dynamical_system(
        self,
        param,
        key,
        mask_train,
        mask_query,
        n_samples,
        x_init=None,
        return_traj=False,
        probability_flow=False,
        simulate_anneal_scale_indices=None,
        return_mean=False,
    ):

        assert n_samples > 0

        # compute horizon depending on annealing and rollouts shape
        d = mask_query.shape[-1]
        if self.anneal:
            # perform exactly `n_samples` rollouts and take endpoints as the samples
            rollouts_shape = (n_samples,)
        else:
            # perform rollouts in parallel and thin the trajectory to obtain samples
            rollouts_shape = self.rollouts_shape 

        # initialize drift and diffusion functions based on parameter arguments
        # fix PRNGKey and step to None so that mask is deterministic
        drift = lambda x, t, s : self.drift(
            param=param,
            x=x,
            diffusion_time=t,
            noise_scale=s,
            mask_train=mask_train,
            mask_query=mask_query,
        )
        diffusion = lambda x, t, s : self.diffusion(
            param=param,
            x=x,
            diffusion_time=t,
            noise_scale=s,
            mask_train=mask_train,
            mask_query=mask_query,
        )

        # forward Euler-Maruyama step
        def _explicit_euler_step(carry, _):
            x_t = carry["x"]
            loop_key = carry["key"]

            if self.anneal:
                # offsets the extreme values generated by parameterization
                # score(x, sigma) = - f(x, sigma) / sigma
                stepsize = self.anneal_dt * ((carry["anneal_noise"] / self.anneal_scales[-1]) ** 2)
            else:
                stepsize = self.dt

            # sample Wiener process noise
            # [..., wiener_procs]
            loop_key, loop_subk = random.split(loop_key)
            xi_t = random.normal(loop_subk, shape=(*x_t.shape[:-1], self.wiener_procs))

            # compute next state
            # [..., d]
            assert x_t.shape[-1:] == (d,)
            f = drift(x_t, carry["anneal_time"].astype(jnp.int32), carry["anneal_noise"])
            assert f.shape == x_t.shape, f"{f.shape} {x_t.shape}"
            assert f.shape[:-1] == xi_t.shape[:-1], f"{f.shape} {xi_t.shape}"

            # [..., d, wiener_procs]
            sigma = diffusion(x_t, carry["anneal_time"].astype(jnp.int32), carry["anneal_noise"])
            assert sigma.shape[-2:] == (d, self.wiener_procs)
            assert f.shape == sigma.shape[:-1], f"{f.shape} {sigma.shape}"

            # [..., d]
            sigma_vec = jnp.einsum("...dw,...w->...d", sigma, xi_t)
            assert sigma_vec.shape == x_t.shape, f"{sigma_vec.shape} {x_t.shape}"

            if probability_flow:
                sigma_vec *= 0.0

            x_t_next = x_t + f * stepsize + sigma_vec * jnp.sqrt(stepsize)

            if self.is_nonnegative:
                x_t_next = jnp.maximum(x_t_next, 0.0)

            carry["x"] = x_t_next
            carry["key"] = loop_key

            # track update statistics
            update = jnp.abs(x_t_next - x_t).mean(-1).mean(0) # mean abs change per dimension
            drift_update = jnp.abs(f).mean(-1).mean(0) # mean abs change per dimension

            carry["___ctr__"] += 1

            delta = update - carry["update___mean__"]
            carry["update___mean__"] += delta / carry["___ctr__"]
            delta2 = update - carry["update___mean__"]
            carry["update___welford_m2__"] += delta * delta2

            drift_delta = drift_update - carry["drift___mean__"]
            carry["drift___mean__"] += drift_delta / carry["___ctr__"]
            drift_delta2 = drift_update - carry["drift___mean__"]
            carry["drift___welford_m2__"] += drift_delta * drift_delta2

            # track state trajectory
            if return_traj:
                state = x_t_next
            else:
                state = None

            return carry, state

        # sample x_init
        # [*rollouts_shape, d]
        assert isinstance(rollouts_shape, tuple), f"`rollouts_shape` has to be a tuple. Got {rollouts_shape}"

        key, subk = random.split(key)
        if x_init is None:
            x_0 = random.normal(subk, shape=(*rollouts_shape, d))
        else:
            if x_init.shape[:-1] == rollouts_shape:
                x_0 = x_init
            elif x_init.ndim == 1 and x_init.shape == (d,):
                x_0 = jnp.tile(x_init[None], (*rollouts_shape, 1))
            elif x_init.ndim == 2 and x_init.shape == (d,):
                idx = random.choice(subk, x_init.shape[0], shape=(*rollouts_shape,), replace=True)
                x_0 = x_init[idx]
            else:
                raise ValueError(f"Invalid x_init shape: {x_init.shape}")

        if self.is_nonnegative:
            x_0 = jnp.abs(x_0)

        carry_init = dict(
            x=x_0,
            key=subk,
            anneal_time=jnp.array(-1),
            anneal_noise=jnp.array(0.0),
            log=dict(),
        )

        log_init = dict(
            ___ctr__=jnp.array(0),
            update___mean__=jnp.array(0.0),
            update___welford_m2__=jnp.array(0.0),
            drift___mean__=jnp.array(0.0),
            drift___welford_m2__=jnp.array(0.0),
        )
        carry_init.update(log_init)

        if return_traj:
            if self.anneal:
                carry_init["x_traj"] = jnp.zeros((self.anneal_steps, *rollouts_shape, d))
            else:
                carry_init["x_traj"] = jnp.zeros((self.thinning, *rollouts_shape, d))

        if self.anneal:
            assert self.anneal_scales is not None

            # perform exactly `n_samples` rollouts and take endpoints as the samples
            # iterate in chunks of `anneal_steps` steps, where each chunk has the same noise level
            def _euler_annealed(carry, anneal_param):
                carry["anneal_time"], carry["anneal_noise"] = anneal_param
                carry.update(log_init)
                carry, states = lax.scan(_explicit_euler_step, carry, None, length=self.anneal_steps)
                if return_traj:
                    carry["x_traj"] = states
                return carry, carry

            anneal_params = onp.stack([
                onp.arange(len(self.anneal_scales)),
                self.anneal_scales,
            ]).T

            if simulate_anneal_scale_indices is not None:
                assert simulate_anneal_scale_indices.ndim == 1
                anneal_params = anneal_params[simulate_anneal_scale_indices]

            # x: [anneal_scales, n_samples, d]
            # x_traj: [anneal_scales, anneal_steps, n_samples, d]
            _, thinned_traj = lax.scan(_euler_annealed, carry_init, anneal_params, length=None)
            assert thinned_traj["x"].shape == (len(anneal_params), n_samples, d)

            # keep only the last annealing step as samples and discard bookkeeping variables from carry trajectory tuple
            samples = thinned_traj["x"][-1, :, :]
            log = thinned_traj["log"]

            if return_traj:
                log["x_traj"] = thinned_traj["x_traj"]

            # compute simulation statistics
            log["update_mean"] = thinned_traj["update___mean__"]
            log["update_std"] = jnp.sqrt(thinned_traj["update___welford_m2__"] / thinned_traj["___ctr__"])

            log["drift_mean"] = thinned_traj["drift___mean__"]
            log["drift_std"] = jnp.sqrt(thinned_traj["drift___welford_m2__"] / thinned_traj["___ctr__"])

            log["samples_mean"] = jnp.mean(thinned_traj["x"], axis=-2)
            log["samples_std"] = jnp.std(thinned_traj["x"], axis=-2)

        else:
            # perform rollouts in parallel and thin the trajectories to obtain samples
            # iterate in chunks of `thinning` steps to keep memory footprint of trajectory returned by lax.scan low
            def _euler_thinned(carry, _):
                carry, states = lax.scan(_explicit_euler_step, carry, None, length=self.thinning)
                if return_traj:
                    carry["x_traj"] = states
                return carry, carry

            # run approximation in `n_samples_per_rollout` chunks of `thinning` steps
            # traj: [n_samples_per_rollout, *rollouts_shape, d]
            n_rollouts = math.prod(self.rollouts_shape)
            n_samples_per_rollout = math.ceil((n_samples / n_rollouts) + self.n_samples_burnin)
            _, thinned_traj = lax.scan(_euler_thinned, carry_init, None, length=n_samples_per_rollout)
            assert thinned_traj["x"].shape == (n_samples_per_rollout, *rollouts_shape, d)

            # move rollout axes to front, s.t. x trajectory has shape [*rollouts_shape, n_samples_per_rollout, d]
            samples = jnp.moveaxis(thinned_traj["x"], 0, len(rollouts_shape))
            samples = samples[..., self.n_samples_burnin:, :]

            # fold random rollouts into the samples axis
            # [n_samples, d]
            samples = samples.reshape(-1, d)
            log = thinned_traj["log"]

            if return_traj:
                log["x_traj"] = thinned_traj["x_traj"]

        if return_mean:
            samples = jnp.mean(samples, axis=0, keepdims=True)

        return samples, log


    def sample_dynamical_system(
        self,
        param,
        key,
        mask_train,
        mask_query,
        *,
        n_samples,
        return_mean=False,
        return_log=False,
    ):
        assert n_samples > 0
        assert mask_query.ndim == 2
        n_envs, d = mask_query.shape
        if n_envs == 0:
            return (jnp.zeros((0, n_samples, d)), None) if return_log else jnp.zeros((0, n_samples, d))

        # simulate trajectories, vmapping over envs specified by intv_theta and mask_query
        # use vmap_chunk to_numpy to avoid initializing large buffers on the accelerator
        # traj["x"]: [n_envs, n_samples_per_rollout, config.rollouts_shape, d]
        _simulate = vmap_chunk(
            functools.partial(self._simulate_dynamical_system,
                              n_samples=n_samples,
                              return_mean=return_mean,
                              return_traj=False),
            in_axes=(None, 0, None, 0),
            out_axes=0,
            chunk_size=self.sim_env_chunk_size,
            to_numpy=True,
        )

        key, *subkeys = random.split(key, n_envs + 1)
        subkeys = jnp.array(subkeys)
        samples, log = _simulate(
            param,
            subkeys,
            mask_train,
            mask_query,
        )

        # permute samples and ensure we have exactly `n_samples` samples when `n_samples % rollouts_shape` is nonzero
        if not return_mean:
            key, subk = random.split(key)
            perm = onp.array(random.permutation(subk, samples.shape[1]))
            samples = samples[:, perm[:n_samples], :]

        if return_log:
            # [n_envs, n_samples, d], pytree
            return samples, log
        else:
            # [n_envs, n_samples, d]
            return samples